server:
  port: 8085

spring:
  application:
    name: mango-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}
  boot:
    admin:
      client:
        url: "http://localhost:8082"
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&zeroDataTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    userName: root
    password: ddx19920930

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#ribbon 负载均衡策略选择, service-producer为注册的服务名
service-producer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #这里选择随机策略(RandomRule)

#开启熔断器
feign:
  hystrix:
    enabled: true